revert ghcr changes

diff --git a/.github/workflows/full-accessibility-audit.yml b/.github/workflows/full-accessibility-audit.yml
--- a/.github/workflows/full-accessibility-audit.yml
+++ b/.github/workflows/full-accessibility-audit.yml
@@ -6,7 +6,6 @@ env:
   APP_PORT: 5173
   # provide the correct port and host flags for your local server
   START_COMMAND: "npx vite --port 5173 --host"
-  AUDIT_IMAGE: ghcr.io/stackoverflowisbetterthananyai/full-accessibility-audit:latest
 
 jobs:
   Full_Accessibility_Audit:
@@ -15,26 +14,45 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Start App
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "24"
+
+      - name: Install Dependencies & Start App
         run: |
           npm ci
+          echo "Starting Local Server"
           $START_COMMAND &
-          npx wait-on http://localhost:$APP_PORT --timeout 60000
 
-      - name: Run Full Accessibility Audit from Registry
+          echo "Waiting for local Port $APP_PORT"
+          npx wait-on http://localhost:$APP_PORT --timeout 60000
+          echo "Server can be reached locally"
+
+      - name: Debug Network Info
+        run: |
+          echo "Host IP Information:"
+          ip addr | grep eth0
+          echo "Check if Port $APP_PORT can be reached"
+          sudo lsof -i :$APP_PORT || echo "Port $APP_PORT cannot be reached"
+
+      - name: Run Full Accessibility Audit With Docker
         run: |
           mkdir -p reports
-          cp cypress/fixtures/sitemap.json reports/sitemap.json || echo "{}" > reports/sitemap.json
+          cp cypress/fixtures/sitemap.json reports/sitemap.json || echo "No existing sitemap found"
+          docker build -t full-accessibility-audit .
 
           GATEWAY_IP=$(docker network inspect bridge -f '{{ (index .IPAM.Config 0).Gateway }}')
+          echo "Gateway IP is: $GATEWAY_IP"
 
           docker run --rm \
             --ipc=host \
             -e CYPRESS_BASE_URL="http://$GATEWAY_IP:$APP_PORT" \
             --add-host=host.docker.internal:host-gateway \
             -v ${{ github.workspace }}/reports:/app/cypress/fixtures \
-            $AUDIT_IMAGE \
+            full-accessibility-audit \
             sh -c "
+              echo 'Waiting for connection to $GATEWAY_IP:$APP_PORT' && \
               npx wait-on http://$GATEWAY_IP:$APP_PORT --timeout 60000 && \
               npm run cy:run-crawler && \
               npm run cy:run-audit
